### PR TITLE
[CLI] Improved Resources Terminate Command 

### PR DESCRIPTION
**Pull request by rcvalerio**
### Expected Behavior:

- The CLI command `inductiva resources terminate --all` should terminate the machine groups in parallel. Currently, it terminates each machine sequentially.
- Additionally, it should list the resources that will be terminated.

Current output:
```
$ inductiva resources terminate --all
You are about to terminate ALL resources.
Are you sure you want to proceed (y/[N])? y
Terminating MachineGroup(name="api-7f2r7imzrxug8rteh8qycx84y"). This may take a few minutes.
Machine Group api-7f2r7imzrxug8rteh8qycx84y with c3d-highcpu-30 machines successfully terminated in 0:01:18.
Terminating MachineGroup(name="api-mwn0xx6eq3pq19fgu3d51nidu"). This may take a few minutes.
Machine Group api-mwn0xx6eq3pq19fgu3d51nidu with c3d-highcpu-4 machines successfully terminated in 0:01:16.
Terminating MachineGroup(name="api-nfim2sro1ovgeodzeq6mw3xau"). This may take a few minutes.
Machine Group api-nfim2sro1ovgeodzeq6mw3xau with c3d-highcpu-4 machines successfully terminated in 0:01:15.
Terminating MachineGroup(name="api-p6uo0s9mcimmzv2a2t42r286k"). This may take a few minutes.
Machine Group api-p6uo0s9mcimmzv2a2t42r286k with c3d-highcpu-4 machines successfully terminated in 0:01:09.
```

### Changes implemented:
- If there is more than one machine to be terminated, the termination is now done in parallel using threads.
- One thread is created for each machine to be removed, with a safety limit of 32 threads.
- The message for the --all command has been updated to display the machines that will be removed (or the number of machines if there are more than 5).

Output with the new changes:
```
$ inductiva resources terminate --all                        
You are about to terminate the following resources:
  - api-cgxaxawfstran71xszgserpb2
  - api-cd0imcswv8f46mf8eqvuh9whk
  - api-8u4z3ypf09dpd7krm2893t271
  - api-cef4169p84mdoe0bm819rj1x2
  - api-4wo9mr6bef16ofeaqux51oqa5
Are you sure you want to proceed (y/[N])? y
Terminating MachineGroup(name="api-cgxaxawfstran71xszgserpb2"). This may take a few minutes.
Terminating MachineGroup(name="api-cd0imcswv8f46mf8eqvuh9whk"). This may take a few minutes.
Terminating MachineGroup(name="api-8u4z3ypf09dpd7krm2893t271"). This may take a few minutes.
Terminating MachineGroup(name="api-cef4169p84mdoe0bm819rj1x2"). This may take a few minutes.
Terminating MachineGroup(name="api-4wo9mr6bef16ofeaqux51oqa5"). This may take a few minutes.
Machine Group api-cd0imcswv8f46mf8eqvuh9whk with c3d-highcpu-30 machines successfully terminated in 0:01:10.
Machine Group api-8u4z3ypf09dpd7krm2893t271 with c3d-highcpu-4 machines successfully terminated in 0:01:11.
Machine Group api-cef4169p84mdoe0bm819rj1x2 with c3d-highcpu-4 machines successfully terminated in 0:01:14.
Machine Group api-4wo9mr6bef16ofeaqux51oqa5 with c3d-highcpu-4 machines successfully terminated in 0:01:15.
Machine Group api-cgxaxawfstran71xszgserpb2 with c3d-highcpu-4 machines successfully terminated in 0:01:18.
```

### CODE REVIEW

**Comment by hpenedones** [comment]
Thanks @rcvalerio ! Let's just wait for @sergiomsantos to validate!

**Review by sergiomsantos — APPROVED** [review]
this task was kinda refined today with Claudia, without us knowing that a fix was already up for it.
The fix does make the process parallel but does not solve the more fundamental issues which are the need for N calls to the backend, one per resource, and the fact that each call is synchronous (the client waits for the resource to be effectively terminated before it returns).

Please add a reference to this PR in the ticket.

**Comment by sergiomsantos** [comment]
> @rcvalerio, the backend now doesn't block waiting for the resource to be terminated, so the parallelization part probably isn't needed anymore.

@luispcunha Can we ask for multiple terminations in the same http request? or do we need a single request per machine group?

**Comment by rcvalerio** [comment]
I will close the pull request since the problem has already been solved

**Comment by rcvalerio** [comment]
> > I will close the pull request since the problem has already been solved
> 
> Wouldn't this bring also the improvements to the logs? My PR did not include that.

You’re right. By the way, to ensure completeness, shouldn’t we also extend the improvements to `inductiva tasks kill` and `inductiva storage remove`?

**Comment by sergiomsantos** [comment]
@rcvalerio 

> You’re right. By the way, to ensure completeness, shouldn’t we also extend the improvements to `inductiva tasks kill` and `inductiva storage remove`?

@rcvalerio I'll add it to the backlog. Thanks

**Pull request closed without merging**
