### PR TITLE
Fix websocket client

### PR DESCRIPTION
**Pull request by bgregoinductiva**

### CODE REVIEW

**Review by hpenedones — APPROVED** [review]
Uau, that was a truly surgical intervention! Nice.

**Review by Pbarbosa92 — APPROVED** [review]
So, what did change to break this ?

**Comment by Pbarbosa92** [comment]
I just tested this. We manage to connect now. But we still get no logs.

Maybe it has something to do with the computation started status.

**Comment by bgregoinductiva** [comment]
> So, what did change to break this ?

Unfortunately we are not sure. Somehow the URL encode was not being done correctly.

**Pull request merged**
