### PR TITLE
Merge Development branch to Main

### PR DESCRIPTION
**Pull request by begaiym-k**
Moving code in development to main.

### CODE REVIEW

**Review by IvanPombo — APPROVED** [review]
LGTM! Most changes that can provide failure are coming in from the backend, the rest was duly tested during development. 

Let's merge and test fully before putting in the PyPi.

**Comment by begaiym-k** [comment]
Pushing 142 files at once is not a great idea, but that's how many changes we did to the Development branch in the last one and a half months! 

Before I merge this, I want to ask each developer of each scenario (or whatever part was your responsibility) to go over the code and make sure that everything is in place. It is important because as I can see now, some of the developers pushed their code to main while others did so to development branches, and there is a very high risk of getting things wrong at this stage. When there are so many changes done it is impossible to go through all of them for one or two people.

**Comment by IvanPombo** [comment]
With the latest changes of this branch, every scenario is working smoothly! Moreover, the PyPI package is running with the default machines. There might be some changes like the storage that aren't yet in this PR.

**Review by Joao97ribeiro — APPROVED** [review]
I tested the FEniCSx scenario, and it's working both with and without the machine groups! Thanks @begaiym-k , great job! 🚀

**Comment by lneves-ai** [comment]
we will hold on this for a bit to allow testing the client against the new backend dev-infrastructure (whose deployment is in progress)

**Pull request merged**
