### PR TITLE
[ProteinSolvation] Deal with Ipython kernel in protein visualizations

### PR DESCRIPTION
**Pull request by david451lima**
Now, in the visualization post-processing the functions that require an interactive visualization check, we check for an ipython kernel. If that is not detected then the code raises an error. If the ipython kernel is detected to be of google.cloud, then the code 
enables the widgets for the viz to be outputed.

Note: If google.cloud is detected in the kernel it's required to import the google.cloab module. Is it not recommended to do it as it stands in the code? Please check it and give feedback

### CODE REVIEW

**Comment by sarmento** [comment]
This is good.
How did you check this?
Can you send the link to notebooks where this rest detects both situations?

**Comment by david451lima** [comment]
> This is good.
> How did you check this?
> Can you send the link to notebooks where this rest detects both situations?

The following code snippet:

```python
import IPython
shell = IPython.get_ipython()
```
Gives the following values for the shell:
<google.colab._shell.Shell object at 0x7b405f32a0b0> in GoogleColab
None in the terminal
<ipykernel.zmqshell.ZMQInteractiveShell object at 0x1058d0670> in Jupyter

**Comment by sarmento** [comment]
> > This is good.
> > How did you check this?
> > Can you send the link to notebooks where this rest detects both situations?
> 
> The following code snippet:
> 
> ```python
> import IPython
> shell = IPython.get_ipython()
> ```
> 
> Gives the following values for the shell: <google.colab._shell.Shell object at 0x7b405f32a0b0> in GoogleColab None in the terminal <ipykernel.zmqshell.ZMQInteractiveShell object at 0x1058d0670> in Jupyter

This is great! Now I see it working.
Next time, would you pls mind adding a section on your PR header where you show exactly this so that reviewers can see what you mean and know that you did the minimal amount of testing?

**Comment by david451lima** [comment]
> > > This is good.
> > > How did you check this?
> > > Can you send the link to notebooks where this rest detects both situations?
> > 
> > 
> > The following code snippet:
> > ```python
> > import IPython
> > shell = IPython.get_ipython()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Gives the following values for the shell: <google.colab._shell.Shell object at 0x7b405f32a0b0> in GoogleColab None in the terminal <ipykernel.zmqshell.ZMQInteractiveShell object at 0x1058d0670> in Jupyter
> 
> This is great! Now I see it working. Next time, would you pls mind adding a section on your PR header where you show exactly this so that reviewers can see what you mean and know that you did the minimal amount of testing?

Yeah you are right, thins info should have been there!

**Comment by sarmento** [comment]
> > > This is good.
> > > How did you check this?
> > > Can you send the link to notebooks where this rest detects both situations?
> > 
> > 
> > The following code snippet:
> > ```python
> > import IPython
> > shell = IPython.get_ipython()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Gives the following values for the shell: <google.colab._shell.Shell object at 0x7b405f32a0b0> in GoogleColab None in the terminal <ipykernel.zmqshell.ZMQInteractiveShell object at 0x1058d0670> in Jupyter
> 
> This is great! Now I see it working. Next time, would you pls mind adding a section on your PR header where you show exactly this so that reviewers can see what you mean and know that you did the minimal amount of testing?

But can you now add some actual test with our code so that i see the error being raised from *our* code?

**Review by IvanPombo — APPROVED** [review]
LGTM! Just address the possibility of doing a test that Sarmento mentioned below.

**Comment by sarmento** [comment]
> > > > > This is good.
> > > > > How did you check this?
> > > > > Can you send the link to notebooks where this rest detects both situations?
> > > > 
> > > > 
> > > > The following code snippet:
> > > > ```python
> > > > import IPython
> > > > shell = IPython.get_ipython()
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Gives the following values for the shell: <google.colab._shell.Shell object at 0x7b405f32a0b0> in GoogleColab None in the terminal <ipykernel.zmqshell.ZMQInteractiveShell object at 0x1058d0670> in Jupyter
> > > 
> > > 
> > > This is great! Now I see it working. Next time, would you pls mind adding a section on your PR header where you show exactly this so that reviewers can see what you mean and know that you did the minimal amount of testing?
> > 
> > 
> > But can you now add some actual test with our code so that i see the error being raised from _our_ code?
> 
> Not sure if I understand. This is heavily dependent of where the user is running the code, do you want to include it in the pytest suite?

What I was trying to say is that, ideally, you would have a jupyter notebook, a google colab, etc opened, you would run on each a piece of code that shows you are testing the case in an actual environment, and then add a printscreen of that to this PR so that we would know that you tested the code in the environments for which you say you solved the problem.

You probably did that, right? I am assuming you tested the code on the notebooks. Just add printscreens here. :)

**Pull request merged**
