### PR TITLE
Fix Synthetic Data for Physics-ML tutorial

### PR DESCRIPTION
**Pull request by rodrigotuna**
This PR fixes typos and unformatted text in the **Synthetic Data for Physics-ML** tutorial.

### CODE REVIEW

**Review by sarmento — APPROVED** [review]
LGTM!

**Comment by hpenedones** [comment]
@Pbarbosa92 : could you please help @rodrigotuna investigate what is failing on the checks:
https://github.com/inductiva/inductiva/actions/runs/10528807899/job/29175177032?pr=1566

Seems like it's trying to run the snippets on the docs and getting:
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'X-Cloud-Trace-Context': 'dbb1a5d4045f89e18fa0b6304fcb8886', 'Date': 'Fri, 23 Aug 2024 16:07:58 GMT', 'Server': 'Google Frontend', 'Content-Length': '38'})
HTTP response body: b'{"detail":"User account is inactive."}'

**Comment by sarmento** [comment]
Yes. That's blocking my PR too....

https://github.com/inductiva/inductiva/actions/runs/10554151416/job/29235532211

**Comment by Pbarbosa92** [comment]
> @Pbarbosa92 : could you please help @rodrigotuna investigate what is failing on the checks: https://github.com/inductiva/inductiva/actions/runs/10528807899/job/29175177032?pr=1566
> 
> Seems like it's trying to run the snippets on the docs and getting: Reason: Unauthorized HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'X-Cloud-Trace-Context': 'dbb1a5d4045f89e18fa0b6304fcb8886', 'Date': 'Fri, 23 Aug 2024 16:07:58 GMT', 'Server': 'Google Frontend', 'Content-Length': '38'}) HTTP response body: b'{"detail":"User account is inactive."}'

This is happening on our markdown sample. We run some code present on that markdown (a normal simulation) and it turns our that the account used to run this code is inactive. We need to talk to the back end and see what is going on with that account.

**Comment by hpenedones** [comment]
> > @Pbarbosa92 : could you please help @rodrigotuna investigate what is failing on the checks: https://github.com/inductiva/inductiva/actions/runs/10528807899/job/29175177032?pr=1566
> > Seems like it's trying to run the snippets on the docs and getting: Reason: Unauthorized HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'X-Cloud-Trace-Context': 'dbb1a5d4045f89e18fa0b6304fcb8886', 'Date': 'Fri, 23 Aug 2024 16:07:58 GMT', 'Server': 'Google Frontend', 'Content-Length': '38'}) HTTP response body: b'{"detail":"User account is inactive."}'
> 
> This is happening on our markdown sample. We run some code present on that markdown (a normal simulation) and it turns our that the account used to run this code is inactive. We need to talk to the back end and see what is going on with that account.

@bgregoinductiva or @luispcunha : can you help?

**Comment by bgregoinductiva** [comment]
> > > @Pbarbosa92 : could you please help @rodrigotuna investigate what is failing on the checks: https://github.com/inductiva/inductiva/actions/runs/10528807899/job/29175177032?pr=1566
> > > Seems like it's trying to run the snippets on the docs and getting: Reason: Unauthorized HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'X-Cloud-Trace-Context': 'dbb1a5d4045f89e18fa0b6304fcb8886', 'Date': 'Fri, 23 Aug 2024 16:07:58 GMT', 'Server': 'Google Frontend', 'Content-Length': '38'}) HTTP response body: b'{"detail":"User account is inactive."}'
> > 
> > 
> > This is happening on our markdown sample. We run some code present on that markdown (a normal simulation) and it turns our that the account used to run this code is inactive. We need to talk to the back end and see what is going on with that account.
> 
> @bgregoinductiva or @luispcunha : can you help?

That is already fixed. What is failing now is the link checker.

**Comment by sarmento** [comment]
Let's pls make sure we have this documented @ClaudiaRSilva  was unaware of the existence of these special "users".

**Comment by ClaudiaRSilva** [comment]
The importance of having this documented is not for the PM to know, but for the dev team to acknowledge and avoid (human) error in situations like these

**Pull request merged**
