### PR TITLE
[Coastal dynamics] Move files related to coastal dynamics simulations

### PR DESCRIPTION
**Pull request by fabiocruz**
This PR moves files in the package such that coastal dynamics utilities are accessible at a higher level than before, namely the scenario, simulator and other helper classes.

One can now access these classes via the `coastal` submodule, e.g.:

```python
import inductiva

bathymetry = inductiva.coastal.Bathymetry(...)
scenario = inductiva.coastal.CoastalArea(bathymetry=bathymetry, ...)
```

For further context, see #520.

### CODE REVIEW

**Review by IvanPombo — COMMENTED** [review]
Overall the code is correct and I approve it! 
However, this change raises a question: the DualSPHysics is a simulator that can be used for coastal dynamics and other of fluids simulations. Another example, for the future will be FEniCS, that it is not just specific for structural mechanics. Even OpenFOAM has some capabilities for structural mechanics. Only Gromacs and SplishSplash are kinda correct at the moment.

So this change only thinks about SWASH and XBeach, and won't make much sense with the current nature of the package. An idea is to move all the simulators to a folder that is not specific of the nature (fluids, molecules, etc...). Hence, `fluids`, `molecules`,..., would be just for the scenarios. 

Wdyt @hpenedones @fabiocruz @sarmento ?

**Comment by fabiocruz** [comment]
I agree, we need to move them out of use-case-specific directories. Finding a way to group them is a challenge, though. We could group them per "simulation method", e.g. FVM, FEM, SPH, for instance. Or at least those that are usable in more than one use-case and/or field.

**Comment by IvanPombo** [comment]
But we could also just do it in an overall folder of simulators. 

My idea would be to have
'inductiva.simulators.openfoam()' and not 'inductiva.simulators.fvm.openfoam()'. 

Wdyt?

**Comment by fabiocruz** [comment]
I think it should be fine for now to keep them all under one directory. However, it's hard to imagine that scaling well to hundreds of simulators... We can always find ways to group them when it becomes an issue, so I'm ok with merging them all into one directory for now.

**Comment by IvanPombo** [comment]
> I think it should be fine for now to keep them all under one directory. However, it's hard to imagine that scaling well to hundreds of simulators... We can always find ways to group them when it becomes an issue, so I'm ok with merging them all into one directory for now.

Let's move with the one directory approach for now, since it is the one making the most sense and thereafter we check when hundreds of simulations are added.

**Comment by fabiocruz** [comment]
> > I think it should be fine for now to keep them all under one directory. However, it's hard to imagine that scaling well to hundreds of simulators... We can always find ways to group them when it becomes an issue, so I'm ok with merging them all into one directory for now.
> 
> Let's move with the one directory approach for now, since it is the one making the most sense and thereafter we check when hundreds of simulations are added.

Sure, I can do that in a separate PR.

**Pull request merged**
