### PR TITLE
Renames types.Path -> str

### PR DESCRIPTION
**Pull request by Franreno**
Closes [#138](https://github.com/inductiva/tasks/issues/138)

### CODE REVIEW

**Comment by hpenedones** [comment]
Thanks @Franreno , I've been discussing with @sergiomsantos that we should actually try to get rid of these custom types for paths -- we shouldn't need to define a new type for things that are very standard. We will try to consolidate everything, potentially just using strings, which is one of the types we accept anyways -- and that's enough, no need to support multiple variants.

**Comment by Franreno** [comment]
> Thanks @Franreno , I've been discussing with @sergiomsantos that we should actually try to get rid of these custom types for paths -- we shouldn't need to define a new type for things that are very standard. We will try to consolidate everything, potentially just using strings, which is one of the types we accept anyways -- and that's enough, no need to support multiple variants.

Thanks for the feedback @hpenedones. I've started a refactor to change from `PathOrStr` to only `str`.  I've also added some tests to some old code that didn't had tests.

**Review by Pbarbosa92 — APPROVED** [review]
LGTM, but we need to test this thoroughly.

**Comment by Pbarbosa92** [comment]
**QA**

I have tested this PR and everything works perfectly for me.

I ran multiple simulations using `str` as the `input_dir` and successfully downloaded the outputs. Additionally, I downloaded the outputs using the CLI without any issues. Using both filenames and `output_dir` as `str` also worked flawlessly.

**Review by sergiomsantos — APPROVED** [review]

**Pull request merged**
