### PR TITLE
Get docs version from env var instead of git branch

### PR DESCRIPTION
**Pull request by tiagoafpereira**
Previous [method](9ccaeca81ffbd4def924e78901b38f658fcea956) of determining the docs version was a bit too clever for it's own good and did not produce the expected results ('unknown_version' was returned instead of the expected 'latest').

This PR simplifies the algorithm: it simply uses environment variables read from `docs/.env`.

### CODE REVIEW

**Review by sergiomsantos — COMMENTED** [review]
how do we differentiate between latest and development? do we need to change the env file all the time?

**Comment by tiagoafpereira** [comment]
Now that you mention it I need to re-add .env to .gitignore otherwise there will be conflicts in the merge from main > development

**Comment by tiagoafpereira** [comment]
@sergiomsantos found a better solution: leverage `sphinx-build` -D argument that enables overriding variables in `conf.py`.

My previous suggestion of setting a `.env` would not work because there would _always_ be conflicts when merging/rebasing like you've mentioned in your previous [comment](https://github.com/inductiva/inductiva/pull/1302#pullrequestreview-1979478399).

**Review by sergiomsantos — APPROVED** [review]
LGTM.
Thanks

**Pull request merged**
