### PR TITLE
Put table horizontal to fix empty space on the side

### PR DESCRIPTION
**Pull request by cristianacarpinteiro**

### CODE REVIEW

**Comment by IvanPombo** [comment]
On the phone it does not look good... so I think we should keep the vertical one.

**Comment by cristianacarpinteiro** [comment]
Horizontal looks like this : image
But if the formatting on the phone is worse, we can keep it vertical.

**Comment by hpenedones** [comment]
I think that Sarmento's suggestion was somewhere in between those two options: if we have 4 scenarios, let's do a 2x2 table. I know that there is the detail of the headers with the names of the scenarios, so I am not sure how the rendering would look like.

**Comment by cristianacarpinteiro** [comment]
@hpenedones like this? 
image

**Comment by hpenedones** [comment]
yes!!  :) great!

**Review by hpenedones — APPROVED** [review]

**Pull request merged**
