### PR TITLE
Move stellarators to plasmas

### PR DESCRIPTION
**Pull request by IvanPombo**

### CODE REVIEW

**Review by sarmento — COMMENTED** [review]
Can you please test this?
Can you run the code Joao wrote?

**Comment by IvanPombo** [comment]
> Can you please test this? Can you run the code Joao wrote?

On it now!

**Comment by IvanPombo** [comment]
> > Can you please test this? Can you run the code Joao wrote?
> 
> On it now!

It's alive and doing well!

**Review by luispcunha — APPROVED** [review]

**Comment by sarmento** [comment]
> > > Can you please test this? Can you run the code Joao wrote?
> > 
> > 
> > On it now!
> 
> It's alive and doing well!

What is the minimal piece of code that would test this? Can you add it as a pytest?

**Comment by IvanPombo** [comment]
> > > > Can you please test this? Can you run the code Joao wrote?
> > > 
> > > 
> > > On it now!
> > 
> > 
> > It's alive and doing well!
> 
> What is the minimal piece of code that would test this? Can you add it as a pytest?

To test scenarios/simulators we need machines available and api_keys for them. Me and @luispcunha are already thinking about these things and devising a way for these tests to be run with github actions. I will open an issue for this discussion and to establish action points.

**Comment by sarmento** [comment]
> > > > > Can you please test this? Can you run the code Joao wrote?
> > > > 
> > > > 
> > > > On it now!
> > > 
> > > 
> > > It's alive and doing well!
> > 
> > 
> > What is the minimal piece of code that would test this? Can you add it as a pytest?
> 
> To test scenarios/simulators we need machines available and api_keys for them. Me and @luispcunha are already thinking about these things and devising a way for these tests to be run with github actions. I will open an issue for this discussion and to establish action points.

Ok. Please do. Thank you.

**Comment by sarmento** [comment]
> > > > > > Can you please test this? Can you run the code Joao wrote?
> > > > > 
> > > > > 
> > > > > On it now!
> > > > 
> > > > 
> > > > It's alive and doing well!
> > > 
> > > 
> > > What is the minimal piece of code that would test this? Can you add it as a pytest?
> > 
> > 
> > To test scenarios/simulators we need machines available and api_keys for them. Me and @luispcunha are already thinking about these things and devising a way for these tests to be run with github actions. I will open an issue for this discussion and to establish action points.
> 
> Ok. Please do. Thank you.

But in any case, on this sort of PR please add a section on: how did i test this?

**Pull request merged**
